Repository api-platform/demo, pull requests merged in 2018-10, with the labels that each got.

#52 Update deployment
  .circleci/config.yml
  .travis.yml
  api/docker/php/docker-entrypoint.sh
  ci/.env
  ci/admin_deploy.sh
  ci/before_deploy.sh
  ci/before_install.sh
  ci/build_image.sh
  ci/check_ci_env_vars.sh
  ci/client_deploy.sh
  ci/deploy.sh
  ci/test.sh
Labels: RFR

#64 Redo change CONTAINER_REGISTRY_BASE
  .env
Labels: bug

#57 Add jest-junit
  ci/test.sh
  client/package.json
  client/yarn.lock
Labels: RFR, enhancement

#63 Add books list feature as example
  client/src/Theme.js
  client/src/Welcome.js
  client/src/actions/book/list.js
  client/src/components/book/List.js
  client/src/components/book/index.js
  client/src/index.js
  client/src/reducers/book/index.js
  client/src/reducers/book/list.js
  client/src/routes/book.js
  client/src/theme.css
  client/src/utils/fetch.js
  client/src/utils/helpers.js
Labels: RFR

#56 Configure eslint
  ci/test.sh
  client/.eslintrc
  client/package.json
  client/yarn.lock
Labels: RFR, enhancement
