Repository api-platform/demo, pull requests merged in 2019-01, with the labels that each got.

#73 Switch to the new Symfony .env structure
  api/.env
  api/.env.dist
  api/.gitignore
  api/Dockerfile
  api/behat.yml.dist
  api/bin/console
  api/composer.json
  api/config/bootstrap.php
  api/features/bootstrap/bootstrap.php
  api/src/Kernel.php
  docker-compose.yml
Labels: RFR

#59 Update documentation
  api/.gitignore
  docs/CONTRIBUTING.md
Labels: RFR, enhancement

#60 Fix #58: support uuid
  api/.env
  api/behat.yml.dist
  api/composer.json
  api/composer.lock
  api/config/bundles.php
  api/config/packages/doctrine_migrations.yaml
  api/config/packages/test/doctrine.yaml
  api/config/services.yaml
  api/features/books.feature
  api/features/bootstrap/BookContext.php
  api/features/bootstrap/FeatureContext.php
  api/src/Entity/Book.php
  api/src/Entity/Parchment.php
  api/src/Entity/Review.php
  api/src/Migrations/Version20181019075654.php
  api/symfony.lock
  ci/test.sh
Labels: RFR, enhancement

#55 Add Puppeteer
  ci/before_deploy.sh
  ci/before_install.sh
  ci/deploy.sh
  ci/test.sh
  client/.dockerignore
  client/.gitignore
  client/Dockerfile
  client/docker/docker-entrypoint.sh
  client/features/features/books.feature
  client/features/hooks.js
  client/features/pages/book.js
  client/features/pages/index.js
  client/features/screenshots/.gitignore
  client/features/server.js
  client/features/step_definitions/books.js
  client/features/support/assert.js
  client/features/support/form.js
  client/features/support/index.js
  client/features/support/navigation.js
  client/features/support/scope.js
  client/features/world.js
  client/package.json
  client/yarn.lock
Labels: RFR, enhancement

#83 Add mercure helm configuration
  api/config/packages/api_platform.yaml
  api/helm/api/templates/configmap.yaml
  api/helm/api/templates/mercure-deployment.yaml
  api/helm/api/templates/mercure-service.yaml
  api/helm/api/templates/php-deployment.yaml
  api/helm/api/templates/secrets.yaml
  api/helm/api/values.yaml
  ci/deploy.sh
Labels: RFR

#86 Remove useless buttons on client
  client/src/Welcome.js
Labels: RFR

#87 Dynamically create secrets for postgres + php secret + mercure jwt
  .travis.yml
  api/helm/api/templates/secrets.yaml
  api/helm/api/values.yaml
  ci/deploy.sh
Labels: RFR

#81 Add Blackfire
  .travis.yml
  api/Dockerfile
  api/helm/api/requirements.yaml
  api/helm/api/values.yaml
  ci/before_install.sh
  ci/deploy.sh
Labels: WIP

#95 Feature deploy
  .gitattributes
  .travis.yml
  README.md
  api/composer.json
  api/composer.lock
  api/config/packages/ramsey_uuid_doctrine.yaml
  api/helm/api/requirements.yaml
  api/helm/api/templates/configmap.yaml
  api/helm/api/templates/demo-ip.yaml
  api/helm/api/templates/ingress.yaml
  api/helm/api/templates/secrets.yaml
  api/helm/api/values.yaml
  api/public/index.php
  api/src/Entity/Book.php
  api/src/Entity/Parchment.php
  api/src/Entity/Review.php
  api/src/Migrations/.gitignore
  api/src/Migrations/Version20181019075654.php
  api/symfony.lock
  ci/.env
  ci/before_deploy
  ci/before_deploy.sh
  ci/before_install.sh
  ci/clean
  ci/deploy
  ci/deploy.sh
  ci/test
  ci/test.sh
  docker-compose.yml
Labels: RFR

#98 Add project name label in namespace
  .travis.yml
  ci/before_deploy
  ci/clean
  ci/deploy
  ci/test
Labels: RFR, bug
